# Generated by Django 3.1.1 on 2020-10-10 22:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20201010_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('form_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='ResponseQuestion',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('response', models.CharField(max_length=255)),
                ('response_id', models.UUIDField()),
            ],
        ),
    ]
