# Generated by Django 3.1.1 on 2020-10-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_response_responsequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsequestion',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsequestion',
            name='question_id',
            field=models.UUIDField(),
        ),
    ]
