# Generated by Django 3.1.1 on 2020-10-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20201010_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
