# Generated by Django 3.1.1 on 2020-11-02 04:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_form_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('form_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('question_id', models.UUIDField()),
            ],
        ),
    ]
