# Generated by Django 3.1.1 on 2020-11-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_multiplechoicefield_multiplechoiceoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfield',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoicefield',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
