# Generated by Django 3.1.1 on 2020-11-17 23:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_auto_20201117_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inputfield',
            name='id',
        ),
        migrations.RemoveField(
            model_name='multiplechoicefield',
            name='id',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceoption',
            name='id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='id',
        ),
        migrations.AlterField(
            model_name='form',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='multiplechoicefield',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='multiplechoiceoption',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
