# Generated by Django 3.1.1 on 2020-11-17 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_auto_20201117_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='temp_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='inputfield',
            old_name='temp_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='multiplechoicefield',
            old_name='temp_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='multiplechoiceoption',
            old_name='temp_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='temp_id',
            new_name='id',
        ),
    ]
