# Generated by Django 3.1.1 on 2020-11-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_auto_20201117_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='form_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='multiplechoicefield',
            name='form_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='multiplechoicefield',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceoption',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceoption',
            name='question_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='response',
            name='form_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='responsequestion',
            name='question_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='responsequestion',
            name='response_id',
            field=models.IntegerField(),
        ),
    ]
